### ISSUE TITLE
Error with React testing library

### ISSUE THREAD

**Issue by Nerevar123** [wellyshen/react-cool-dimensions#558]
# Bug Report

I`m using ResizeObserver Polyfill for testing with React testing library, tests passed successfully,  but still have a console.error:

setupTests.ts 

> import { ResizeObserver } from '@juggle/resize-observer';
> 
> window.ResizeObserver = ResizeObserver;
> Element.prototype.scrollTo = jest.fn();

Error: 

> console.error
> 💡 react-cool-dimensions: the browser doesn't support Resize Observer, please use polyfill: https://github.com/wellyshen/react-cool-dimensions#resizeobserver-polyfill

```
  at node_modules/react-cool-dimensions/dist/index.js:1:2420
  at invokePassiveEffectCreate (node_modules/react-dom/cjs/react-dom.development.js:23487:20)
  at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
  at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
  at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
  at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
  at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
  at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
```

## Your Environment

> "react": "^17.0.2",
> "@testing-library/jest-dom": "^5.11.4"
> "@testing-library/react": "^11.1.0"
> "react-cool-dimensions":  "1.3.4"
>

**Comment by wellyshen** [comment]
@Nerevar123 Not sure if the global setup of jest is correct or not, but you can refer to my [setup](https://github.com/wellyshen/react-cool-dimensions/blob/master/src/__tests__/useDimensions.ts#L38).
